# Generated by Django 4.1.4 on 2023-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('details', models.CharField(max_length=250)),
                ('interest', models.CharField(choices=[('not interested', 'Not interested'), ('interested', 'interested')], default='not interested', max_length=15)),
                ('calling', models.CharField(choices=[('not', 'Not called'), ('called', 'called')], default='not', max_length=15)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
